package org.rivierarobotics.frcgrantle.tasks

import org.gradle.api.DefaultTask
import org.gradle.api.artifacts.Configuration
import org.gradle.api.artifacts.Dependency
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.Internal
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction

import static org.rivierarobotics.frcgrantle.Const.FRC_COMPILE

class FirstAntConfig extends DefaultTask {

    private File userLibsDir = project.file('build/frclibs/user')
    private File wpilibNativeDir = project.file('build/.frclibs/wpilib')
    private Dependency cscoreJar
    private Dependency networkTablesJar
    private Dependency opencvJar
    private Dependency wpilibJar

    private File buildPropertiesFile = project.file('build.properties');

    {
        group = 'FRC'
    }

    @Input
    File getUserLibsDir() {
        return userLibsDir
    }

    void setUserLibsDir(File userLibsDir) {
        this.userLibsDir = userLibsDir
    }

    void userLibsDir(File userLibsDir) {
        setUserLibsDir(userLibsDir)
    }

    @Input
    File getWpilibNativeDir() {
        return wpilibNativeDir
    }

    void setWpilibNativeDir(File wpilibNativeDir) {
        this.wpilibNativeDir = wpilibNativeDir
    }

    void wpilibNativeDir(File wpilibNativeDir) {
        setWpilibNativeDir(wpilibNativeDir)
    }

    @Internal
    Dependency getCscoreJar() {
        return cscoreJar
    }

    void setCscoreJar(Dependency cscoreJar) {
        this.cscoreJar = cscoreJar
    }

    void cscoreJar(Dependency cscoreJar) {
        setCscoreJar(cscoreJar)
    }

    @Internal
    Dependency getNetworkTablesJar() {
        return networkTablesJar
    }

    void setNetworkTablesJar(Dependency networkTablesJar) {
        this.networkTablesJar = networkTablesJar
    }

    void networkTablesJar(Dependency networkTablesJar) {
        setNetworkTablesJar(networkTablesJar)
    }

    @Internal
    Dependency getOpencvJar() {
        return opencvJar
    }

    void setOpencvJar(Dependency opencvJar) {
        this.opencvJar = opencvJar
    }

    void opencvJar(Dependency opencvJar) {
        setOpencvJar(opencvJar)
    }

    @Internal
    Dependency getWpilibJar() {
        return wpilibJar
    }

    void setWpilibJar(Dependency wpilibJar) {
        this.wpilibJar = wpilibJar
    }

    void wpilibJar(Dependency wpilibJar) {
        setWpilibJar(wpilibJar)
    }

    @Input
    Configuration getConfiguration() {
        return project.configurations.getByName(FRC_COMPILE)
    }

    @OutputFile
    File getBuildPropertiesFile() {
        return buildPropertiesFile
    }

    private static void ensureDirectoryExists(File dir) {
        if (!dir.mkdirs() && !dir.isDirectory()) {
            throw new IllegalStateException("Unable to create directory ${dir.absolutePath}")
        }
    }

    @TaskAction
    void configureFirstAnt() {
        ensureDirectoryExists(userLibsDir)
        ensureDirectoryExists(wpilibNativeDir)
        def antProperties = new Properties()
        antProperties['userLibs.dir'] = userLibsDir.absolutePath
        antProperties['wpilib.native.lib'] = wpilibNativeDir.absolutePath

        // grab libraries
        def compile = configuration

        // check resolve
        compile.resolvedConfiguration.rethrowFailure()

        antProperties['cscore.jar'] = compile.files(cscoreJar).first().absolutePath
        antProperties['networktables.jar'] = compile.files(networkTablesJar).first().absolutePath
        antProperties['opencv.jar'] = compile.files(opencvJar).first().absolutePath
        antProperties['wpilib.jar'] = compile.files(wpilibJar).first().absolutePath


        buildPropertiesFile.withOutputStream {
            antProperties.store(it, "Generated by FRC Grantle.")
        }
    }

}
